server:
 port: 4212
 compression:
   enabled: true
   mime-types: application/json,application/xml
   min-response-size: 500
 servlet:
   context-path: /v1

spring:
  data:
    mongodb:
        uri: mongodb://127.0.0.1:27017
        database: alfred
  http:
    encoding:
      enabled: true
      charset: utf-8